CREATE TABLE nijibase.member_list(
   name         VARCHAR(17) NOT NULL PRIMARY KEY
  ,branch       VARCHAR(10) NOT NULL
  ,debut_3d     BIT  NOT NULL
  ,nick         INTEGER  NOT NULL
  ,social_media INTEGER  NOT NULL
  ,illustrator  VARCHAR(57)
  ,visual       VARCHAR(31) NOT NULL
);
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Tsukino Mito','Japan',1,1,1,'https://twitter.com/nezumidosi_','https://i.imgur.com/xvvqX6e.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Higuchi Kaede','Japan',1,2,2,'https://twitter.com/yasumo01','https://i.imgur.com/uoobhgJ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shizuka Rin','Japan',1,3,3,'https://twitter.com/v_loAlo','https://i.imgur.com/R4SsiTI.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yuki Chihiro','Japan',1,4,4,'https://twitter.com/yasumo01','https://i.imgur.com/xfZsdZ3.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Eru','Japan',1,5,5,'https://twitter.com/u_skeeep','https://i.imgur.com/Uke7sCP.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shibuya Hajime','Japan',0,6,6,'https://twitter.com/mamimumemonoma','https://i.imgur.com/POkUv27.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Moira','Japan',1,7,7,'https://twitter.com/nezumidosi_','https://i.imgur.com/sSajAxW.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Suzuya Aki','Japan',0,8,8,'https://twitter.com/nezumidosi_','https://i.imgur.com/U6UEIUS.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ienaga Mugi','Japan',1,9,9,'https://twitter.com/nano_phan','https://i.imgur.com/KEPgfzV.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yuuhi Riri','Japan',0,10,10,'https://twitter.com/nezumidosi_','https://i.imgur.com/wjB8tyg.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Fushimi Gaku','Japan',0,11,11,'https://twitter.com/mamimumemonoma','https://i.imgur.com/ifOG6lK.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kenmochi Touya','Japan',1,12,12,'https://twitter.com/mamimumemonoma','https://i.imgur.com/uJEgT7J.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Mononobe Alice','Japan',1,13,13,'https://twitter.com/yuta_moeki/status/1036982758113832960','https://i.imgur.com/2Lh7r5K.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Suzuka Utako','Japan',1,14,14,'https://twitter.com/nezumidosi_','https://i.imgur.com/UJk0ywo.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ushimi Ichigo','Japan',1,15,15,'https://twitter.com/methyl_key','https://i.imgur.com/HzGbOSM.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Gilzaren III','Japan',0,16,16,'https://twitter.com/sousuke2434','https://i.imgur.com/tGrJJtV.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Fumino Tamaki','Japan',0,17,17,'https://twitter.com/nezumidosi_','https://i.imgur.com/QvsuYfb.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Morinaka Kazaki','Japan',1,18,18,'https://twitter.com/mori70','https://i.imgur.com/M4TMm2E.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kanae','Japan',1,19,19,'https://twitter.com/u_skeeep','https://i.imgur.com/x6E0QqL.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Akabane Youko','Japan',0,20,20,'https://twitter.com/nagomi_759','https://i.imgur.com/CTKNSHA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yashiro Kizuku','Japan',1,21,21,'https://twitter.com/otototo_','https://i.imgur.com/bV1pa1u.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Sister Claire','Japan',1,22,22,'https://twitter.com/mamimumemonoma','https://i.imgur.com/5GbIfpF.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Dola','Japan',1,23,23,'https://twitter.com/geronimp00','https://i.imgur.com/RiKDJir.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Todoroki Kyouko','Japan',0,24,24,'https://twitter.com/mamimumemonoma','https://i.imgur.com/qgA3u5U.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Azuchi Momo','Japan',0,25,25,'https://twitter.com/heatinazuma','https://i.imgur.com/Z5lFMDs.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Uzuki Kou','Japan',0,26,26,'https://twitter.com/yuzuki3se','https://i.imgur.com/LEWafMd.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Suzuki Masaru','Japan',0,27,27,'https://twitter.com/rikak','https://i.imgur.com/nyhx4mX.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ryuushen','Japan',1,28,28,'https://twitter.com/koga_kmdd','https://i.imgur.com/Zx6b3oV.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Izumo Kasumi','Japan',0,29,29,'https://twitter.com/u_skeeep','https://i.imgur.com/8FjTRQq.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hanabatake Chaika','Japan',1,30,30,'https://twitter.com/ikuyoan','https://i.imgur.com/3T2jqJw.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Naruse Naru','Japan',0,31,31,NULL,'https://i.imgur.com/AL0Hn7L.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Harusaki Air','Japan',0,32,32,'https://twitter.com/koga_kmdd','https://i.imgur.com/ao3f8Ie.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Sasaki Saku','Japan',1,33,33,'https://twitter.com/yasumo01','https://i.imgur.com/b050eTF.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Honma Himawari','Japan',1,34,34,'https://twitter.com/yasumo01','https://i.imgur.com/lcisXAl.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Makaino Ririmu','Japan',0,35,35,'https://twitter.com/lalalalack','https://i.imgur.com/CHKhUav.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kuzuha','Japan',1,36,36,'https://twitter.com/v_loAlo','https://i.imgur.com/UvAXRyL.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shiina Yuika','Japan',1,37,37,'https://twitter.com/kami_shun0505','https://i.imgur.com/yYJCtTu.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Takamiya Rion','Japan',1,38,38,'https://twitter.com/kemo_9_1_sailor','https://i.imgur.com/zaAowTe.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Maimoto Keisuke','Japan',1,39,39,'https://twitter.com/otototo_','https://i.imgur.com/Ie12Kvu.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shoichi Kanda','Japan',0,40,40,'https://twitter.com/yuzuyu7cat','https://i.imgur.com/JSmj7qQ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Amemori Sayo','Japan',0,41,41,'https://twitter.com/mamimumemonoma','https://i.imgur.com/4ANUCto.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Asuka Hina','Japan',0,42,42,'https://twitter.com/kemo_9_1_sailor','https://i.imgur.com/UCnihB0.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Rindou Mikoto','Japan',1,43,43,'https://twitter.com/asahi_nini','https://i.imgur.com/dDXdo5z.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Debidebi Debiru','Japan',1,44,44,'https://twitter.com/rollsheeeep','https://i.imgur.com/6OGT1cv.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Sakura Ritsuki','Japan',1,45,45,'https://twitter.com/Hario_4','https://i.imgur.com/niOWQPP.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Machita Chima','Japan',0,46,46,'https://twitter.com/aru9a3','https://i.imgur.com/zcdJP7k.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Joe Rikiichi','Japan',1,47,47,'https://twitter.com/minoru_sudou','https://i.imgur.com/oaIu0FP.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yumeoi Kakeru','Japan',1,48,48,'https://twitter.com/mamimumemonoma','https://i.imgur.com/VyPFqkA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kuroi Shiba','Japan',0,49,49,NULL,'https://i.imgur.com/4owMurW.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yaguruma Rine','Japan',0,50,50,'https://twitter.com/methyl_key','https://i.imgur.com/qZwWlDS.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Belmond Banderas','Japan',1,51,51,'https://twitter.com/sousuke2434','https://i.imgur.com/71UNpYD.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Warabeda Meiji','Japan',1,52,52,'https://twitter.com/yuta_moeki','https://i.imgur.com/nBP8CwC.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yuzuki Roa','Japan',1,53,53,'https://twitter.com/OnFb20','https://i.imgur.com/T4hWkR6.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Gundou Mirei','Japan',1,54,54,'https://twitter.com/nagomi_759','https://i.imgur.com/b3SB2in.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Onomachi Haruka','Japan',0,55,55,'https://twitter.com/vert_320','https://i.imgur.com/5Iil0gx.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kataribe Tsumugu','Japan',0,56,56,'https://twitter.com/rollsheeeep','https://i.imgur.com/CUYmur5.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Seto Miyako','Japan',0,57,57,'https://twitter.com/kaya7hara','https://i.imgur.com/Ll62q8G.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Otogibara Era','Japan',1,58,58,'https://twitter.com/yuta_moeki','https://i.imgur.com/xfNA2Bb.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Inui Toko','Japan',1,59,59,'https://twitter.com/__y_o_u_k_a__','https://i.imgur.com/LLE8vua.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ange Katrina','Japan',1,60,60,'https://twitter.com/kwgc_c','https://i.imgur.com/3fLsFQf.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Lize Helesta','Japan',1,61,61,'https://twitter.com/fuzichoco','https://i.imgur.com/A5DLbKX.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Aizono Manami','Japan',0,62,62,'https://twitter.com/itolife','https://i.imgur.com/LiW0B9K.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Saegusa Akina','Japan',0,63,63,'https://twitter.com/esasi8794','https://i.imgur.com/oXWy0cA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Suzuhara Lulu','Japan',1,64,64,'https://twitter.com/sainexxx','https://i.imgur.com/amyiBj9.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yukishiro Mahiro','Japan',0,65,65,'https://twitter.com/nano_phan','https://i.imgur.com/xA7RZBn.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ex Albio','Japan',1,66,66,'https://twitter.com/KSUWABE','https://i.imgur.com/LjrJEhq.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Levi Elipha','Japan',0,67,67,'https://twitter.com/ki0000llll','https://i.imgur.com/jEyr2gQ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hayama Marin','Japan',1,68,68,'https://twitter.com/fumi_411','https://i.imgur.com/qyzKBRD.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nui Sociere','Japan',1,69,69,'https://twitter.com/kanzarinsan','https://i.imgur.com/cRSDOFF.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hakase Fuyuki','Japan',1,70,70,'https://twitter.com/vane0','https://i.imgur.com/MyOaV0S.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kagami Hayato','Japan',1,71,71,'https://twitter.com/fuyuomi','https://i.imgur.com/yxuAMIK.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yorumi Rena','Japan',1,72,72,'https://twitter.com/TeraAru6262','https://i.imgur.com/rQUFCBG.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Mayuzumi Kai','Japan',1,73,73,'https://twitter.com/1ji9_1109','https://i.imgur.com/vkyI5YX.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ars Almal','Japan',1,74,74,'https://twitter.com/Par1y','https://i.imgur.com/Tx2qXUr.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Aiba Uiha','Japan',0,75,75,'https://twitter.com/poppin_phl95','https://i.imgur.com/JU0Ydbo.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Amamiya Kokoro','Japan',0,76,76,'https://twitter.com/shior2','https://i.imgur.com/QHLl9fx.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Eli Conifer','Japan',0,77,77,'https://twitter.com/aba_ame0','https://i.imgur.com/6TdRvlE.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ratna Petit','Japan',0,78,78,'https://twitter.com/nishinoda','https://i.imgur.com/OIZ6JRs.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hayase Sou','Japan',0,79,79,'https://twitter.com/ha_ni_w','https://i.imgur.com/5QYBe4K.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Sukoya Kana','Japan',1,80,80,'https://twitter.com/kaya7hara','https://i.imgur.com/6RVHeF3.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shellin Burgundy','Japan',1,81,81,'https://twitter.com/fuka_hire','https://i.imgur.com/PsFF4Du.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hoshikawa Sara','Japan',1,82,82,'https://twitter.com/kasu1923','https://i.imgur.com/8rnNhnT.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Fumi','Japan',0,83,83,'https://twitter.com/yuzuyu7cat','https://i.imgur.com/PzmLgpw.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yamagami Karuta','Japan',0,84,84,'https://twitter.com/vane0','https://i.imgur.com/ukshrpd.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Emma August','Japan',0,85,85,'https://twitter.com/shiratamacaron','https://i.imgur.com/xshDNSd.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Matsukai Mao','Japan',0,86,86,'https://twitter.com/UedaHuku','https://i.imgur.com/IsGJFy9.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Luis Cammy','Japan',0,87,87,'https://twitter.com/Hario_4','https://i.imgur.com/U33gY7g.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Fuwa Minato','Japan',1,88,88,'https://twitter.com/tomatsukaze','https://i.imgur.com/VIclHeX.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shirayuki Tomoe','Japan',0,89,89,'https://twitter.com/morimokimori','https://i.imgur.com/P9VSLGI.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Gwelu Os Gar','Japan',0,90,90,'https://twitter.com/ikuyoan','https://i.imgur.com/ukfFPCF.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Mashiro','Japan',0,91,91,NULL,'https://i.imgur.com/to2Mcfp.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Naraka','Japan',0,92,92,'https://twitter.com/ana_ame0','https://i.imgur.com/HVKFmVB.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kurusu Natsume','Japan',0,93,93,'https://twitter.com/cowardly_bug','https://i.imgur.com/foJtcL7.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Furen E Lustario','Japan',1,94,94,'https://twitter.com/SHUTOCHIKACHIKA','https://i.imgur.com/81h6Dw0.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Melissa Kinrenka','Japan',1,95,95,NULL,'https://i.imgur.com/sgdK8eX.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ibrahim','Japan',1,96,96,'https://twitter.com/takerunamito','https://i.imgur.com/8IHgLAa.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nagao Kei','Japan',0,97,97,'https://twitter.com/v_loAlo','https://i.imgur.com/awvnsm5.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kaida Haru','Japan',0,98,98,'https://twitter.com/AiRM320','https://i.imgur.com/8nQS02E.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Genzuki Tojiro','Japan',0,99,99,'https://twitter.com/becco2','https://i.imgur.com/AUz0akJ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Sorahoshi Kirame','Japan',0,100,100,'https://twitter.com/oshio_dayo','https://i.imgur.com/F896peD.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Asahina Akane','Japan',0,101,101,'https://twitter.com/eihi','https://i.imgur.com/kGikuDH.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Suo Sango','Japan',0,102,102,'https://twitter.com/ha_tak','https://i.imgur.com/d4ElfxF.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Todo Kohaku','Japan',0,103,103,'https://twitter.com/umiko35','https://i.imgur.com/cEp3Rts.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kitakoji Hisui','Japan',0,104,104,NULL,'https://i.imgur.com/kWU2XIw.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nishizono Chigusa','Japan',0,105,105,'https://twitter.com/AC______','https://i.imgur.com/QfWXCAD.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Wiffy','Korea',0,106,106,'https://twitter.com/patoritori','https://i.imgur.com/yNIGTGr.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shin Yuya','Korea',0,107,107,'https://twitter.com/6nnnnnn9','https://i.imgur.com/sOpp8QU.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Min Suha','Korea',0,108,108,'https://twitter.com/yoshinowataru','https://i.imgur.com/IfbvsCm.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Han Chiho','Korea',0,109,109,'https://twitter.com/ANNS2_S2','https://i.imgur.com/cbfcJcy.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Gaon','Korea',0,110,110,NULL,'https://i.imgur.com/d9nInTV.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Lee Siu','Korea',0,111,111,'https://twitter.com/lemon_mito','https://i.imgur.com/KIenG9p.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('So Nagi','Korea',0,112,112,'https://twitter.com/fumomo_','https://i.imgur.com/8kT3tle.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Chae Ara','Korea',0,113,113,'https://twitter.com/poppin_phl95','https://i.imgur.com/8j0QlOK.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Akira Ray','Korea',0,114,114,'https://twitter.com/01masami13','https://i.imgur.com/1tv3VLT.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Lee Roha','Korea',0,115,115,'https://twitter.com/ttomarii','https://i.imgur.com/IyIfuqP.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nun Bora','Korea',0,116,116,'https://twitter.com/dbk67251371','https://i.imgur.com/osR54wf.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ryu Hari','Korea',0,117,117,'https://twitter.com/TeraAru6262','https://i.imgur.com/VjsgrgG.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Oh Jiyu','Korea',0,118,118,'https://twitter.com/ss0neyy','https://i.imgur.com/efgOiwx.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shin Kiru','Korea',0,119,119,'https://twitter.com/ss0neyy','https://i.imgur.com/sIeOo6p.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yang Nari','Korea',0,120,120,'https://twitter.com/soratobuiltusa','https://i.imgur.com/CgEgrWb.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hana Macchia','Indonesia',0,121,121,NULL,'https://i.imgur.com/sfUxEMW.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Zea Cornelia','Indonesia',0,122,122,NULL,'https://i.imgur.com/DWSV6XA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Taka Radjiman','Indonesia',0,123,123,NULL,'https://i.imgur.com/XzV3Hdi.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Rai Galilei','Indonesia',0,124,124,NULL,'https://i.imgur.com/h4AGHIZ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Riksa Dhirendra','Indonesia',0,125,125,NULL,'https://i.imgur.com/jrOCxbF.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Amicia Michella','Indonesia',0,126,126,NULL,'https://i.imgur.com/KNQLFno.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Miyu Ottavia','Indonesia',0,127,127,NULL,'https://i.imgur.com/o6NVEVa.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Azura Cecilia','Indonesia',0,128,128,NULL,'https://i.imgur.com/XVbCvHK.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Layla Alstromeria','Indonesia',0,129,129,NULL,'https://i.imgur.com/Z60EaC0.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nara Haramaung','Indonesia',0,130,130,NULL,'https://i.imgur.com/Tuxz3sr.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Etna Crimson','Indonesia',0,131,131,NULL,'https://i.imgur.com/FZFzAZA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Bonnivier Pranaja','Indonesia',0,132,132,NULL,'https://i.imgur.com/S8iU8yC.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Siska Leontyne','Indonesia',0,133,133,NULL,'https://i.imgur.com/0cRQcpI.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nagisa Arcinia','Indonesia',0,134,134,'https://twitter.com/Ikazu401','https://i.imgur.com/SCFzklV.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Derem Kado','Indonesia',0,135,135,'https://twitter.com/kraukraukrau','https://i.imgur.com/RXaJ5Lm.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Reza Avanluna','Indonesia',0,136,136,'https://twitter.com/kraukraukrau','https://i.imgur.com/zggnlOg.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Aadya','EN',0,137,137,NULL,'https://i.imgur.com/31O3EIi.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Noor','EN',0,138,138,NULL,'https://i.imgur.com/iYuFAtq.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Vihaan','EN',0,139,139,NULL,'https://i.imgur.com/kcQugTK.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Eine','VirtuaReal',0,140,140,NULL,'https://i.imgur.com/pUAY5d7.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ruki','VirtuaReal',0,141,141,NULL,'https://i.imgur.com/K4eRto7.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nanami','VirtuaReal',0,142,142,NULL,'https://i.imgur.com/VZ5Kz0x.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Ichigo','VirtuaReal',0,143,143,NULL,'https://i.imgur.com/bYWnp8T.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kouichi','VirtuaReal',0,144,144,NULL,'https://i.imgur.com/en8yboD.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Muri','VirtuaReal',0,145,145,NULL,'https://i.imgur.com/3xyNSuQ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Plus','VirtuaReal',0,146,146,NULL,'https://i.imgur.com/GPW5wPu.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Nyatsuki','VirtuaReal',0,147,147,NULL,'https://i.imgur.com/0Wy1Q7Y.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Waku','VirtuaReal',0,148,148,NULL,'https://i.imgur.com/CZ9Vbfh.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Miki','VirtuaReal',0,149,149,NULL,'https://i.imgur.com/WQJYAzo.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Hoshimi','VirtuaReal',0,150,150,NULL,'https://i.imgur.com/FGY6Xbz.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Mahiru','VirtuaReal',0,151,151,NULL,'https://i.imgur.com/PuZ1FQL.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Aza','VirtuaReal',0,152,152,NULL,'https://i.imgur.com/vtYZLYO.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yagi','VirtuaReal',0,153,153,NULL,'https://i.imgur.com/kgxEEdi.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Tabibito','VirtuaReal',0,154,154,NULL,'https://i.imgur.com/xFdxaUZ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Roi','VirtuaReal',0,155,155,NULL,'https://i.imgur.com/sh3xVw5.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Karu','VirtuaReal',0,156,156,NULL,'https://i.imgur.com/a9p7Rml.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Samael','VirtuaReal',0,157,157,NULL,'https://i.imgur.com/NOxnwE6.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shiki','VirtuaReal',0,158,158,NULL,'https://i.imgur.com/nBdYqbX.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Seiya','VirtuaReal',0,159,159,NULL,'https://i.imgur.com/91xTKTA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yukie','VirtuaReal',0,160,160,NULL,'https://i.imgur.com/9wAeV2v.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Saya','VirtuaReal',0,161,161,NULL,'https://i.imgur.com/1pP0ByN.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Chaos','VirtuaReal',0,162,162,NULL,'https://i.imgur.com/lhSyBIt.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Kiyora','VirtuaReal',0,163,163,NULL,'https://i.imgur.com/Jpnq2OD.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Chiharu','VirtuaReal',0,164,164,NULL,'https://i.imgur.com/FicHP6V.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Reve','VirtuaReal',0,165,165,NULL,'https://i.imgur.com/1GHw5Pe.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Sirius','VirtuaReal',0,166,166,NULL,'https://i.imgur.com/norCcwZ.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Yua','VirtuaReal',0,167,167,NULL,'https://i.imgur.com/JUnUauA.png');
INSERT INTO nijibase.member_list(name,branch,debut_3d,nick,social_media,illustrator,visual) VALUES ('Shaun','VirtuaReal',0,168,168,NULL,'https://i.imgur.com/Mjgy4by.png');
