CREATE TABLE nijibase.nickname(
   id_real  INTEGER  NOT NULL PRIMARY KEY 
  ,nick_id  INTEGER  NOT NULL
  ,nickname VARCHAR(183) NOT NULL
);
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (1,1,'Iinchou');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (2,2,'Deron');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (3,3,'Shizurin');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (4,4,'Chii');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (5,5,'Elu');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (6,6,'Hajiki');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (7,7,'Moimoi');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (8,8,'Akikun');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (9,17,'Noraneko');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (10,19,'Kana');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (11,19,'Kanakana');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (12,20,'Banego');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (13,21,'yskz');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (14,21,'yashikizu');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (15,27,'Darkness Eater');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (16,28,'Midori');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (17,33,'ssk');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (18,33,'Sasa');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (19,34,'Honhima');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (20,34,'Hima');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (21,37,'Shiishii');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (22,37,'CC');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (23,42,'HinaP');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (24,43,'Warawa');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (25,45,'Ritsukin');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (26,48,'Yumeo');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (27,52,'WRBD');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (28,54,'Sensei');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (29,56,'ktrb');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (30,57,'Setomiya');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (31,57,'Myako');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (32,57,'Myaako');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (33,58,'Gibara');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (34,60,'Nju');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (35,61,'Ize');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (36,63,'Akkeyna');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (37,66,'Ebio');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (38,69,'Nyui');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (39,71,'Shacho');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (40,71,'Shachou');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (41,73,'Mayuyu');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (42,74,'Marumaru');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (43,74,'Manmaru');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (44,76,'Amamya');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (45,76,'Myamya');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (46,76,'Amyamya');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (47,76,'Mya');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (48,78,'Pute');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (49,78,'Putei');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (50,79,'Ran');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (51,79,'Rannee');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (52,79,'Ran-nee');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (53,82,'hskw');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (54,88,'Fuwacchi');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (55,95,'Meli');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (56,95,'Mary');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (57,95,'Meri');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (58,96,'Himura');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (59,96,'Himu');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (60,96,'Ibu');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (61,96,'Ib');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (62,101,'Ako');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (63,102,'Ngo');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (64,104,'Hisupi');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (65,121,'Hanamaki');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (66,123,'Takamama');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (67,125,'Jukut');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (68,126,'Cia');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (69,126,'Amicin');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (70,127,'Mimi');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (71,128,'Zura');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (72,128,'Jura');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (73,129,'Madam');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (74,129,'Layla');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (75,129,'Lele');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (76,132,'Bobon');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (77,136,'Eja');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (78,136,'Awan');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (79,136,'Ejak');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (80,5,'Snow White Paradise El Santo Flow Wasurena Pure Princess Livre Love Heidern Dokodoko Yattaze Valkyria Passion Alfr Noel Chakoboshi Eluaria Frosia Made-in Bloom Elu');
INSERT INTO nijibase.nickname(id_real,nick_id,nickname) VALUES (81,5,'Sunoo howaito paradaisu erusanto furoo wasurena pyua purinsesu riiburu rabu haiderun dokodoko yattaze vu~arukyuria passhon aaruvu noeru chakoboshi eruaria furoojia Meidoin buruumu Eru');
